config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :texts
  resources :comments
  get "/show_pdf/:id", to: 'show_pdf#index', as: "pdf"
  # resources :show_pdf, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/text.rb
class Text < ApplicationRecord
  has_one_attached :document
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def create_tempfile(file)      
    tempfile = Tempfile.open(["temp", ".pdf"])
    tempfile.binmode
    tempfile.write(file)
    tempfile.rewind

    return tempfile
  end


  private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url, status: :see_other
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url, status: :see_other) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user.admin?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:update, :create, :destroy]

  def update
    comment = Comment.find(params[:id])
    if comment.update(comment_params)
      redirect_to edit_text_path(comment.text_id)
    else
      render edit_text_path(comment.text_id), status: :unprocessable_entity
    end
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to edit_text_path(@comment.text_id)
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    Comment.find(params[:id]).destroy
    flash[:success] = "コメントを削除しました"
    redirect_to edit_text_path(comment.text_id), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :highlighted_text, :start_offset, :end_offset, :text_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードが間違っています'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/show_pdf_controller.rb
class ShowPdfController < ApplicationController
  def index
    @text = Text.find(params[:id])
    @comments = Comment.where(text_id: params[:id]).order(start_offset: "ASC")
    @highlighted_texts = @comments.pluck(:highlighted_text).uniq

    # html = render_to_string("show_pdf/index", layout: "pdf")
    # # html = File.read("#{Rails.root}/app/views/show_pdf/index.html.erb")
    # kit = PDFKit.new(html, page_size: 'A4')
    # kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/custom.scss"
    # # kit.javascripts << "#{Rails.root}/app/javascript/application.js"
    # # kit.to_file("#{Rails.root}/public/example.pdf")
    # send_data kit.to_pdf, filename: 'example.pdf', type: 'application/pdf', disposition: 'inline'

    kit = PDFKit.new('https://comment-app-c9kf.onrender.com/texts/' + params[:id])
    kit.to_file("#{Rails.root}/public/example.pdf")
    send_data kit.to_pdf, filename: 'example.pdf', type: 'application/pdf', disposition: 'inline'
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :logged_in_user, only: [:new, :show, :create, :edit, :destroy]

  def new
    @text = Text.new
  end

  def show
    @text = Text.find(params[:id])
    @comments = Comment.where(text_id: params[:id]).order(start_offset: "ASC")
    @highlighted_texts = @comments.pluck(:highlighted_text).uniq
  end

  def create
    @text = Text.new(text_params)
    @text.save
    s3_client = Aws::S3::Client.new(region: ENV["REGION"], access_key_id: ENV["ACCESS_KEY_ID"], secret_access_key: ENV["SECRET_ACCESS_KEY"])
    file = s3_client.get_object(bucket: ENV["BUCKET"], key: @text.document.key).body.read
    tempfile = create_tempfile(file)
    reader = Pdftotext.text(tempfile)
    puts reader
    @text.update(text: reader)
    redirect_to new_text_path
  end

  def edit
    @text = Text.find(params[:id])
    @comments = Comment.where(text_id: params[:id]).order(start_offset: "ASC")
    @highlighted_texts = @comments.pluck(:highlighted_text).uniq
  end

  def destroy
    text = Text.find(params[:id])
    Text.find(params[:id]).destroy
    flash[:success] = "テキストを削除しました"
    redirect_to new_text_path, status: :see_other
  end

  private
  def text_params
    params.require(:text).permit(:text, :document)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "新規登録が完了しました！"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "保存されました"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/show_pdf_helper.rb
module ShowPdfHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <div id="head-manu">
        <% if logged_in? %>
          <%= link_to "ホーム", current_user, class: "btn" %>
          <%= link_to "テキストを追加", new_text_path, class: "btn" %>
          <%= link_to "テキスト一覧", texts_path, class: "btn" %>
          <%= link_to "ユーザー一覧", users_path, class: "btn" %>
          <%= link_to "設定", edit_user_path(current_user), class: "btn" %>
          <%# <%= button_to "ログアウト", logout_path, data: { "turbo-method": :delete}, class: "btn" %>
          <%= button_to "ログアウト", logout_path, method: :delete, data: {turbo: false}, class: "btn" %>
        <% else %>
          <%= link_to "新規登録", new_user_path, class: "btn" %>
          <%= link_to "ログイン", login_path, class: "btn" %>
        <% end %>
      </div>
    </div>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize(@user.errors.count, "つのエラーがあります。") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/show_pdf/index.html.erb
<script>
  var highlightedTexts = <%= raw @highlighted_texts %>;
</script>

<div class="row align-items-center">
  <div class="col">
    <div class="overlay">
      <div id="commentable-text">
        <%= @text.text %>
      </div>
      <div id="highlightable-text">
        <%= @text.text %>
      </div>
    </div>
  </div>

  <div class="col">
    <div id="comments" class="p-3">
      <% @comments.each do |comment| %>
        <div class="comment border border-3 border-info rounded-3 p-2 my-3">
          <div id="comment-show">
            <div>
              コメント：
              <%= comment.comment %>
            </div>
            <div>
              ハイライトするテキスト：
              <%= comment.highlighted_text %>
            </div>
            <div>
              位置情報：
              <%= comment.start_offset %>,<%= comment.end_offset %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/texts/create.html.erb
<h1>Texts#create</h1>
<p>Find me in app/views/texts/create.html.erb</p>

app/views/texts/destroy.html.erb
<h1>Texts#destroy</h1>
<p>Find me in app/views/texts/destroy.html.erb</p>

app/views/texts/edit.html.erb
<script>
  var highlightedTexts = <%= raw @highlighted_texts %>;
</script>

<%# <%= link_to 'PDFを作成', @text, class: "btn", format: :pdf %>

<div class="row align-items-center">
  <div class="col">
    <div class="overlay">
      <div id="commentable-text">
        <%= @text.text %>
      </div>
      <div id="highlightable-text">
        <%= @text.text %>
      </div>
    </div>
    <%= button_to "削除", @text, method: :delete, data: {turbo: false, confirm: "本当に削除しますか？"}, class: "btn btn-outline-danger" %>
  </div>

  <div class="col">
    <div id="comment-form" class="p-3" style="display: none;">
      <%= form_with(model: Comment.new, remote: true, html: { class: 'comment-form' }, data: {turbo: false}) do |form| %>
        <%= form.hidden_field :text_id, value: @text.id %>
        <%= form.text_area :comment, placeholder: 'コメントを入力', rows: 3, class: "form-control" %>
        <%= form.hidden_field :highlighted_text %>
        <%= form.hidden_field :start_offset, id: 'start-offset-field' %>
        <%= form.hidden_field :end_offset, id: 'end-offset-field' %>
        <%= form.submit 'コメントを追加', class: 'btn btn-outline-primary' %>
      <% end %>
    </div>
    <div id="comments" class="p-3">
      <% @comments.each do |comment| %>
        <div class="comment border border-3 border-info rounded-3 p-2 my-3">
          <div id="comment-show">
            <div>
              コメント：
              <%= comment.comment %>
            </div>
            <div>
              ハイライトするテキスト：
              <%= comment.highlighted_text %>
            </div>
            <div>
              位置情報：
              <%= comment.start_offset %>,<%= comment.end_offset %>
            </div>
          </div>
          <div id="comment-edit-form" style="display: none;">
            <%= form_with(model: comment, remote: true, html: { class: 'comment-form' }, data: {turbo: false}) do |form| %>
              <%= form.hidden_field :text_id, value: @text.id %>
              <%= form.text_area :comment, value: comment.comment, rows: 3, class: "form-control" %>
              <%= form.hidden_field :highlighted_text %>
              <%= form.hidden_field :start_offset %>
              <%= form.hidden_field :end_offset %>
              <%= form.submit '更新する', class: 'btn btn-outline-primary' %>
            <% end %>
          </div>
          <span id="comment-edit-btn" class="btn btn-outline-secondary">編集</span>
          <%# <%= link_to "削除", comment, data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"}, class: "btn btn-outline-danger" %>
          <%= button_to "削除", comment, method: :delete, data: {turbo: false, confirm: "本当に削除しますか？"}, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="positionInfo" class="pt-5">
  <p id="selectedText">選択したテキスト内容がここに表示されます。</p>
  <p>選択したテキストの位置情報:</p>
  <p id="startOffset">開始オフセット:</p>
  <p id="endOffset">終了オフセット:</p>
</div>

<div>
  <%= @text.document %>
</div>

app/views/texts/index.html.erb
<h1>Texts#index</h1>
<p>Find me in app/views/texts/index.html.erb</p>

app/views/texts/new.html.erb
<%= form_with model: @text, local: true do |form| %>
  <%= form.text_field :text, class: "form-control", rows: 3 %>
  <%= form.file_field :document, class: "form-control" %>
  <%= form.submit 'テキストを追加', class: 'btn btn-primary' %>
<% end %>


ある日の暮方の事である。一人の下人げにんが、羅生門らしょうもんの下で雨やみを待っていた。
広い門の下には、この男のほかに誰もいない。ただ、所々丹塗にぬりの剥はげた、大きな円柱まるばしらに、蟋蟀きりぎりすが一匹とまっている。羅生門が、朱雀大路すざくおおじにある以上は、この男のほかにも、雨やみをする市女笠いちめがさや揉烏帽子もみえぼしが、もう二三人はありそうなものである。それが、この男のほかには誰もいない。
何故かと云うと、この二三年、京都には、地震とか辻風つじかぜとか火事とか饑饉とか云う災わざわいがつづいて起った。そこで洛中らくちゅうのさびれ方は一通りではない。旧記によると、仏像や仏具を打砕いて、その丹にがついたり、金銀の箔はくがついたりした木を、路ばたにつみ重ねて、薪たきぎの料しろに売っていたと云う事である。洛中がその始末であるから、羅生門の修理などは、元より誰も捨てて顧る者がなかった。するとその荒れ果てたのをよい事にして、狐狸こりが棲すむ。盗人ぬすびとが棲む。とうとうしまいには、引取り手のない死人を、この門へ持って来て、棄てて行くと云う習慣さえ出来た。そこで、日の目が見えなくなると、誰でも気味を悪るがって、この門の近所へは足ぶみをしない事になってしまったのである。

app/views/texts/show.html.erb
<script>
  var highlightedTexts = <%= raw @highlighted_texts %>;
</script>

<%= link_to "PDFを出力", pdf_path %>

<div class="row align-items-center">
  <div class="col">
    <div class="overlay">
      <div id="commentable-text">
        <%= @text.text %>
      </div>
      <div id="highlightable-text">
        <%= @text.text %>
      </div>
    </div>
  </div>

  <div class="col">
    <div id="comments" class="p-3">
      <% @comments.each do |comment| %>
        <div class="comment border border-3 border-info rounded-3 p-2 my-3">
          <div id="comment-show">
            <div>
              コメント：
              <%= comment.comment %>
            </div>
            <div>
              ハイライトするテキスト：
              <%= comment.highlighted_text %>
            </div>
            <div>
              位置情報：
              <%= comment.start_offset %>,<%= comment.end_offset %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/texts/update.html.erb
<h1>Texts#update</h1>
<p>Find me in app/views/texts/update.html.erb</p>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<div class="row">
  <div class="col">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_message' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "保存する", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<div>
  <% @users.each do |user| %>
    <div>
      <%= link_to user, class: "btn" do%>
        <h3><%= user.name %></h3>
      <% end %>
      <% if current_user.admin? && !current_user?(user) %>
        <%= link_to "削除", user, data: { "turbo-method": :delete, turbo_confirm: "本当に削除しますか？" }, class: "btn" %>
      <% end %>
    </div>
  <% end %>
</div>
<%= will_paginate @users, previous_label: '< 前へ', next_label: '次へ >' %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<div class="">
  <div class="">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_message' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "アカウントを作成する", class: "btn btn-primary" %>
    <% end %>
    <p>ログインは <%= link_to "こちら", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>